spring:
  cloud:
    config:
      enabled: true
    compatibility-verifier:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:./Database/Data/Foyer
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8085
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    tn.esprit.tpfoyer: DEBUG