spring:
  cloud:
    config:
      enabled: true
    compatibility-verifier:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password: password  # Aligné avec docker-compose.yml:reservation-service
    url: jdbc:h2:file:./Database/Data/Reservation;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082

